name: ossc_chat_bot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  upgrader: ^11.3.1
  bot_toast: ^4.1.3
  responsive_sizer: ^3.3.1
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.17
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.3
  smooth_page_indicator: ^1.2.1
  country_code_picker: ^3.2.0
  flutter_bounce: ^1.1.0
  flutter_form_builder: 
  dio: ^5.8.0+1
  http: ^1.1.0
  retrofit: ^4.4.2
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  interval_time_picker: ^3.0.3+9
  syncfusion_flutter_calendar: ^28.2.12
  form_builder_validators: ^11.1.2
  form_validator: ^2.1.1
  dropdown_search: ^5.0.6
  im_stepper: ^1.0.1+1
  image_picker: ^1.1.2
  file_picker: ^9.2.1
  flutter_pdfview: ^1.4.0
  timeago: ^3.7.0
  qr_flutter: ^4.1.0
  timeline_tile: ^2.0.0
  flutter_cached_pdfview: ^0.4.3
  camera: ^0.11.1
  signature: ^6.0.0
  lottie: ^3.3.1
  video_player: ^2.9.5
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.13.1
  dotted_line: ^3.2.3
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  introduction_screen: ^3.1.17

dev_dependencies:
  build_runner:
  flutter_gen_runner: ^5.11.0
  retrofit_generator: ^9.3.0
  json_serializable: ^6.6.2
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true





flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/dm_sans/DMSans-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-VariableFont_opsz,wght.ttf
          weight: 700
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/amharic/washrab.ttf
          weight: 400
      